# Generated by Django 2.2.3 on 2019-07-25 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20190725_1744'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='choice',
            managers=[
            ],
        ),
    ]
